apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-nlb-service
  labels: 
    app: usermgmt-webapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
spec:
  type: LoadBalancer # Default - CLB
  selector:
    app: usermgmt-webapp
  ports: 
    - port: 80
      targetPort: 8080